/**
 * Names flagged as obsolete by the fitness library audit (AdminLife export
 * compared against the rebuilt prop/rugby/5K plan). Consumed by
 * cleanupFitnessLibrary.ts — see that file for how the lists are applied.
 *
 * Matching is exact on the trimmed name, deliberately: several kept names are
 * near-misses of removed ones ("Barbell back squat" vs "Paused barbell back
 * squat", "Trap bar deadlift" vs "Trap-bar deadlift").
 */

/** Exercises to remove entirely — every record carrying the name goes. */
export const EXERCISES_REMOVE_ALL = [
    'Incline barbell bench press',
    'Decline barbell bench press',
    'Incline dumbbell bench press',
    'Dumbbell floor press',
    'Chest press machine',
    'Smith machine bench press',
    'Cable chest fly',
    'Dumbbell chest fly',
    'Pec deck fly',
    'Push-up',
    'Assisted dip',
    'Parallel bar dip',
    'Seated barbell shoulder press',
    'Dumbbell shoulder press',
    'Arnold press',
    'Machine shoulder press',
    'Landmine press',
    'Dumbbell lateral raise',
    'Cable lateral raise',
    'Machine lateral raise',
    'Dumbbell front raise',
    'Cable front raise',
    'Reverse pec deck fly',
    'Bent-over dumbbell reverse fly',
    'Barbell row',
    'Pendlay row',
    'Dumbbell row',
    'Chest-supported dumbbell row',
    'Seated cable row',
    'Close-grip seated cable row',
    'Wide-grip seated cable row',
    'Machine row',
    'T-bar row',
    'Inverted row',
    'Close-grip lat pulldown',
    'Wide-grip lat pulldown',
    'Neutral-grip lat pulldown',
    'Assisted pull-up',
    'Pull-up',
    'Chin-up',
    'Straight-arm cable pulldown',
    'Cable pullover',
    'Dumbbell pullover',
    'Barbell shrug',
    'Dumbbell shrug',
    'Back extension',
    'Barbell front squat',
    'Goblet squat',
    'Smith machine squat',
    'Hack squat',
    'Leg press',
    'Single-leg press',
    'Leg extension',
    'Barbell Romanian deadlift',
    'Dumbbell Romanian deadlift',
    'Conventional deadlift',
    'Sumo deadlift',
    'Rack pull',
    'Lying leg curl',
    'Standing leg curl',
    'Barbell hip thrust',
    'Glute bridge',
    'Cable pull-through',
    'Walking lunge',
    'Reverse lunge',
    'Forward lunge',
    'Dumbbell split squat',
    'Bulgarian split squat',
    'Step-up',
    'Cable hip abduction',
    'Hip abduction machine',
    'Hip adduction machine',
    'Seated calf raise',
    'Leg press calf raise',
    'Barbell biceps curl',
    'EZ-bar biceps curl',
    'Dumbbell biceps curl',
    'Alternating dumbbell curl',
    'Hammer curl',
    'Incline dumbbell curl',
    'Preacher curl',
    'Cable biceps curl',
    'Machine biceps curl',
    'Close-grip bench press',
    'EZ-bar skull crusher',
    'Cable triceps pushdown',
    'Rope triceps pushdown',
    'Cable overhead triceps extension',
    'Triceps dip machine',
    'Cable crunch',
    'Box squat',
    'Pause squat',
    'Barbell walking lunge',
    'Weighted step-up',
    'Lateral lunge',
    'Cossack squat',
    'Single-leg Romanian deadlift',
    'Nordic hamstring curl',
    'Sled push',
    'Heavy sled push',
    'Sled sprint',
    'Backward sled drag',
    'Lateral sled drag',
    'Power clean',
    'Hang power clean',
    'High pull',
    'Landmine push press',
    'Single-arm dumbbell bench press',
    'Weighted pull-up',
    'Neutral-grip pull-up',
    'Suitcase carry',
    'Front rack carry',
    'Bear-hug sandbag carry',
    'Sandbag shoulder carry',
    'Cable woodchop',
    'Landmine rotation',
    'Ab wheel rollout',
    'Weighted plank',
    'Assault bike sprint intervals',
    'Dumbbell skull crusher',
    'Seated or lying leg curl',
    'Standing dumbbell calf raise',
    'Paused barbell back squat',
    'Dumbbell step-up',
    'Trap-bar deadlift',
]

/**
 * Exercises that stay in the library but have a duplicate row. One record is
 * kept — the one most referenced by workouts, oldest as a tie-break — and the
 * rest are removed.
 */
export const EXERCISES_KEEP_ONE = [
    'Barbell back squat',
    'Barbell bench press',
    'Cable face pull',
    'Trap bar deadlift',
]

/** Strength workouts (Workout collection) to remove. */
export const WORKOUTS_REMOVE = [
    'Upper Body Basics',
    'Upper Push',
    'Upper Pull',
    'Upper Strength and Stability',
    'Lower Body Basics',
    'Lower Body Machines',
    'Lower Body Single-Leg',
    'Lower Body Rugby Base',
    'Upper Body A',
    'Upper Body B',
    'Lower Body A',
    'Lower Body B',
    'Upper A - Rugby Size & Strength',
    'Lower A - Heavy Rugby Base',
    'Upper B - Shoulders, Back & Arms',
    'Upper A',
    'Lower A - Main Lower Strength',
    'Upper B - In-Season Friendly',
    'Lower B - Non-Match Week',
    'Pre-Match Rugby Primer',
    'Lower B - Off-Season',
    'Upper B - Off-Season',
    'Lower A - Main Rugby Strength',
    'Upper B - Rugby Upper Body',
    'Rugby Power & Armour',
    'Lower A - Prop Foundation',
    'Upper B - Contact Strength',
    'Cruise Full Body A - Light & Fun',
    'Cruise Full Body B - Light & Fun',
    'Upper A - Post-Match Maintenance',
    'Lower A - Match Block Maintenance',
]

/** Conditioning sessions (ConditioningSession collection) to remove. */
export const CONDITIONING_REMOVE = [
    'Treadmill Week 1 - Mon 3 Aug',
    'Treadmill Week 1 - Wed 5 Aug',
    'Treadmill Week 1 - Fri 7 Aug',
    'Treadmill Week 2 - Mon 10 Aug',
    'Treadmill Week 2 - Wed 12 Aug',
    'Treadmill Week 2 - Fri 14 Aug',
    'Cruise Maintenance - Mon 31 Aug',
    'Cruise Maintenance - Thu 3 Sep',
    'First Outdoor Run - Wed 9 Sep',
    'First Outdoor Run - Fri 11 Sep',
    'Outdoor Week 1 - Mon 14 Sep',
    'Outdoor Week 1 - Wed 16 Sep',
    'Outdoor Week 1 - Fri 18 Sep',
    'Outdoor Week 2 - Mon 21 Sep',
    'Outdoor Week 2 - Wed 23 Sep',
    'Outdoor Week 2 - Fri 25 Sep',
    'Outdoor Week 3 - Mon 28 Sep',
    'Outdoor Week 3 - Wed 30 Sep',
    'Outdoor Week 3 - Fri 2 Oct',
    'Outdoor Week 4 - Mon 5 Oct',
    'Outdoor Week 4 - Wed 7 Oct',
    'Outdoor Week 4 - Fri 9 Oct',
    'Outdoor Week 5 - Mon 12 Oct',
    'Outdoor Week 5 - Wed 14 Oct',
    'Outdoor Week 5 - Fri 16 Oct',
    'Outdoor Week 6 - Mon 19 Oct',
    'Outdoor Week 6 - Wed 21 Oct',
    'Outdoor Week 6 - Fri 23 Oct',
    'Outdoor Week 7 - Mon 26 Oct',
    'Outdoor Week 7 - Wed 28 Oct',
    'Outdoor Week 7 - Fri 30 Oct',
    '5K Goal Week - Mon 2 Nov',
    '5K Goal Week - Wed 4 Nov',
    'First Continuous 5K - Fri 6 Nov',
    'Plyometrics & Movement Session',
    'Treadmill Run-Walk Intervals',
    'Rowing Steady State - Base Building',
    'Rowing Intervals - 5 x 500m',
    'Rowing Pyramid - Progressive Intensity',
    'Bike Steady State - Endurance Ride',
    'Bike Intervals - Tabata Style',
    'Bike Tempo Repeats - Threshold Work',
    'Rowing & Bike Circuit - Mixed Cardio',
    'Rowing Sprint Repeats - Short Power',
    'Bike Climb Intervals - Power & Strength',
    'Bike Steady State - Zone 2 Base Building',
    'Bike Intervals - Tabata Style HIIT',
    'Bike Threshold Repeats - Lactate Work',
    'Bike Climb Intervals - Muscular Endurance',
    'Bike Sprint Repeats - Peak Power',
    'Bike VO2 Max Intervals - Short Hills',
    'Bike Easy Recovery Spin',
    'Bike Progressive Endurance - Distance Build',
    'Bike Tempo Pyramids - Variable Intensity',
    'Outdoor Week 8 - Mon 2 Nov',
    'Outdoor Week 8 - Wed 4 Nov',
    'Outdoor Week 8 - Fri 6 Nov',
    '5K Goal Week - Mon 9 Nov',
    '5K Goal Week - Wed 11 Nov',
    'First Continuous 5K - Fri 13 Nov',
    'Performance Week 1 - Easy Run - Mon 16 Nov',
    'Performance Week 1 - Faster Running - Wed 18 Nov',
    'Performance Week 1 - Long Run - Fri 20 Nov',
    'Performance Week 2 - Easy Run - Mon 23 Nov',
    'Performance Week 2 - Intervals - Wed 25 Nov',
    'Performance Week 2 - Long Run - Fri 27 Nov',
    'Performance Week 3 - Easy Run - Mon 30 Nov',
    'Performance Week 3 - Tempo Intervals - Wed 2 Dec',
    'Performance Week 3 - Long Run - Fri 4 Dec',
    'Performance Week 4 - Easy Run - Mon 7 Dec',
    'Performance Week 4 - Speed Introduction - Wed 9 Dec',
    'Performance Week 4 - Long Run - Fri 11 Dec',
    'Performance Week 5 - Easy Run - Mon 14 Dec',
    'Performance Week 5 - Tempo Intervals - Wed 16 Dec',
    'Performance Week 5 - Long Run - Fri 18 Dec',
    'Performance Week 6 - Easy Run - Mon 21 Dec',
    'Performance Week 6 - Steady Run - Wed 23 Dec',
    'Performance Week 6 - Long Run - Fri 25 Dec',
    'Performance Week 7 - Easy Run - Mon 28 Dec',
    'Performance Week 7 - Threshold Intervals - Wed 30 Dec',
    'Performance Week 7 - Long Run - Fri 1 Jan',
    'Performance Week 8 - Easy Run - Mon 4 Jan',
    'Performance Week 8 - Fartlek - Wed 6 Jan',
    'Performance Week 8 - Long Run - Fri 8 Jan',
    'Performance Week 9 - Easy Run - Mon 11 Jan',
    'Performance Week 9 - Tempo Intervals - Wed 13 Jan',
    'Performance Week 9 - Long Run - Fri 15 Jan',
    'Performance Week 10 - Easy Run - Mon 18 Jan',
    'Performance Week 10 - Threshold Intervals - Wed 20 Jan',
    'Performance Week 10 - Long Run - Fri 22 Jan',
    'Performance Week 11 - Easy Run & Strides - Mon 25 Jan',
    'Performance Week 11 - Continuous Tempo - Wed 27 Jan',
    'Performance Week 11 - Long Run - Fri 29 Jan',
    '10K Goal Week - Easy Run - Mon 1 Feb',
    '10K Goal Week - Easy Run & Strides - Wed 3 Feb',
    'First Continuous 10K - Fri 5 Feb',
    'Wednesday Aerobic Run',
    'Rugby Conditioning - Low Impact Repeat Efforts',
    'Rugby Conditioning - Sled & Bike',
    'Rugby Conditioning - Straight-Line Tempo',
    'Rugby Conditioning - Repeated Efforts',
    'Easy Run - Wed 2 Sep',
    'Bike Intervals',
    'Tuesday Rugby Training',
    'Thursday Rugby Training',
    'Saturday Zone 2 Bike',
    'Saturday Easy Run',
    'Saturday Recovery Cardio',
    'May Rugby Engine - Bike Repeats',
    'May Rugby Engine - Sled & Bike',
    'Saturday Prop Repeat Efforts',
    'Pre-Match Shakeout',
    'Post-Cruise Treadmill - Wed 9 Sep',
    'Post-Cruise Treadmill - Fri 11 Sep',
    'Treadmill Build 1 - Mon 14 Sep',
    'Treadmill Build 1 - Wed 16 Sep',
    'Treadmill Build 2 - Mon 21 Sep',
    'Treadmill Build 2 - Wed 23 Sep',
    'Treadmill Build 2 - Fri 25 Sep',
    'Treadmill Build 3 - Mon 28 Sep',
    'Treadmill Build 3 - Wed 30 Sep',
    'Continuous 3K - Mon 5 Oct',
    'Continuous 3K - Wed 7 Oct',
    'Continuous 3K - Fri 9 Oct',
    'Continuous 3.5K - Mon 12 Oct',
    'Continuous 3.5K - Wed 14 Oct',
    'Continuous 4K - Mon 19 Oct',
    'Continuous 4K - Wed 21 Oct',
    'Continuous 4.5K - Mon 26 Oct',
    'Continuous 4.5K - Wed 28 Oct',
    'Continuous 5K - Mon 2 Nov',
    'Continuous 5K - Wed 4 Nov',
    'Continuous 5K - Fri 6 Nov',
    'Winter Easy Run - Mon 9 Nov',
    'Winter Treadmill Reps - Wed 11 Nov',
    'Winter Easy Run - Mon 16 Nov',
    'Winter Treadmill Reps - Wed 18 Nov',
    'Winter Long Run - Fri 20 Nov',
    'Winter Easy Run - Mon 23 Nov',
    'Winter Treadmill Reps - Wed 25 Nov',
    'Winter Long Run - Fri 27 Nov',
    'Winter Easy Run - Mon 30 Nov',
    'Winter Treadmill Reps - Wed 2 Dec',
    'Winter Easy Run - Mon 7 Dec',
    'Winter Treadmill Reps - Wed 9 Dec',
    'Winter Easy Run - Mon 14 Dec',
    'Winter Treadmill Reps - Wed 16 Dec',
    'Winter Long Run - Fri 18 Dec',
    'Winter Easy Run - Mon 21 Dec',
    'Winter Treadmill Reps - Wed 23 Dec',
    'Winter Long Run - Fri 25 Dec',
    'Winter Easy Run - Mon 28 Dec',
    'Winter Treadmill Reps - Wed 30 Dec',
    'Winter Long Run - Fri 1 Jan',
    'Winter Easy Run - Mon 4 Jan',
    'Winter Treadmill Reps - Wed 6 Jan',
    'Winter Long Run - Fri 8 Jan',
    'Winter Easy Run - Mon 11 Jan',
    'Winter Treadmill Reps - Wed 13 Jan',
    'Winter Easy Run - Mon 18 Jan',
    'Winter Treadmill Reps - Wed 20 Jan',
    'Winter Easy Run - Mon 25 Jan',
    'Winter Treadmill Reps - Wed 27 Jan',
    '10K Goal Week Easy Run - Mon 1 Feb',
    '10K Goal Week Treadmill Reps - Wed 3 Feb',
    'Saturday Easy Maintenance Run',
    'Treadmill Week 2 - Mon 10 Aug - 2026-08-10',
    'Treadmill Week 2 - Wed 12 Aug - 2026-08-12',
    'Treadmill Week 2 - Fri 14 Aug - 2026-08-14',
    'Post-Cruise Treadmill - Wed 9 Sep - 2026-09-09',
    'Post-Cruise Treadmill - Fri 11 Sep - 2026-09-11',
    'Treadmill Build 1 - Mon 14 Sep - 2026-09-14',
    'Treadmill Build 1 - Wed 16 Sep - 2026-09-16',
    'Treadmill Build 2 - Mon 21 Sep - 2026-09-21',
    'Treadmill Build 2 - Wed 23 Sep - 2026-09-23',
    'Treadmill Build 2 - Fri 25 Sep - 2026-09-25',
    'Treadmill Build 3 - Mon 28 Sep - 2026-09-28',
    'Treadmill Build 3 - Wed 30 Sep - 2026-09-30',
    'Continuous 3K - Mon 5 Oct - 2026-10-05',
    'Continuous 3K - Wed 7 Oct - 2026-10-07',
    'Continuous 3K - Fri 9 Oct - 2026-10-09',
    'Continuous 3.5K - Mon 12 Oct - 2026-10-12',
    'Continuous 3.5K - Wed 14 Oct - 2026-10-14',
    'Continuous 4K - Mon 19 Oct - 2026-10-19',
    'Continuous 4K - Wed 21 Oct - 2026-10-21',
    'Continuous 4.5K - Mon 26 Oct - 2026-10-26',
    'Continuous 4.5K - Wed 28 Oct - 2026-10-28',
    'Continuous 5K - Mon 2 Nov - 2026-11-02',
    'Continuous 5K - Wed 4 Nov - 2026-11-04',
    'Continuous 5K - Fri 6 Nov - 2026-11-06',
    'Winter Easy Run - Mon 9 Nov - 2026-11-09',
    'Winter Treadmill Reps - Wed 11 Nov - 2026-11-11',
    'Winter Easy Run - Mon 16 Nov - 2026-11-16',
    'Winter Treadmill Reps - Wed 18 Nov - 2026-11-18',
    'Winter Long Run - Fri 20 Nov - 2026-11-20',
    'Winter Easy Run - Mon 23 Nov - 2026-11-23',
    'Winter Treadmill Reps - Wed 25 Nov - 2026-11-25',
    'Winter Long Run - Fri 27 Nov - 2026-11-27',
    'Winter Easy Run - Mon 30 Nov - 2026-11-30',
    'Winter Treadmill Reps - Wed 2 Dec - 2026-12-02',
    'Winter Easy Run - Mon 7 Dec - 2026-12-07',
    'Winter Treadmill Reps - Wed 9 Dec - 2026-12-09',
    'Winter Easy Run - Mon 14 Dec - 2026-12-14',
    'Winter Treadmill Reps - Wed 16 Dec - 2026-12-16',
    'Winter Long Run - Fri 18 Dec - 2026-12-18',
    'Winter Easy Run - Mon 21 Dec - 2026-12-21',
    'Winter Treadmill Reps - Wed 23 Dec - 2026-12-23',
    'Winter Long Run - Fri 25 Dec - 2026-12-25',
    'Winter Easy Run - Mon 28 Dec - 2026-12-28',
    'Winter Treadmill Reps - Wed 30 Dec - 2026-12-30',
    'Winter Long Run - Fri 1 Jan - 2027-01-01',
    'Winter Easy Run - Mon 4 Jan - 2027-01-04',
    'Winter Treadmill Reps - Wed 6 Jan - 2027-01-06',
    'Winter Long Run - Fri 8 Jan - 2027-01-08',
    'Winter Easy Run - Mon 11 Jan - 2027-01-11',
    'Winter Treadmill Reps - Wed 13 Jan - 2027-01-13',
    'Winter Easy Run - Mon 18 Jan - 2027-01-18',
    'Winter Treadmill Reps - Wed 20 Jan - 2027-01-20',
    'Winter Easy Run - Mon 25 Jan - 2027-01-25',
    'Winter Treadmill Reps - Wed 27 Jan - 2027-01-27',
    '10K Goal Week Easy Run - Mon 1 Feb - 2027-02-01',
    '10K Goal Week Treadmill Reps - Wed 3 Feb - 2027-02-03',
    'First Continuous 10K - Fri 5 Feb - 2027-02-05',
    'Evening Rugby Training',
    'Treadmill Return W1 - Mon 2 Nov',
    'Treadmill Return W1 - Wed 4 Nov',
    'Treadmill Return W2 - Mon 9 Nov',
    'Treadmill Return W2 - Wed 11 Nov',
    'Treadmill Return W3 - Wed 18 Nov',
    'Treadmill Return W4 - Mon 23 Nov',
    'Treadmill Return W4 - Wed 25 Nov',
    'Treadmill Return W5 - Mon 30 Nov',
    'Treadmill Return W5 - Wed 2 Dec',
    'Treadmill Match-Block Aerobic - Wed 9 Dec',
    'Treadmill Return W6 - Wed 16 Dec',
    'Treadmill Return W7 - Mon 21 Dec',
    'Treadmill Return W7 - Wed 23 Dec',
    'Treadmill Continuous 20 - Mon 28 Dec',
    'Treadmill Continuous 20 - Wed 30 Dec',
    'Treadmill Continuous 3K - Mon 4 Jan',
    'Treadmill Continuous 3K - Wed 6 Jan',
    'Treadmill Continuous 3.5K - Mon 11 Jan',
    'Treadmill Continuous 3.5K - Wed 13 Jan',
    'Match-Block Easy Treadmill - Wed 20 Jan',
    'Match-Block Easy Treadmill - Wed 27 Jan',
    'Post-Match Continuous Treadmill - Wed 3 Feb',
    'Wednesday Aerobic Treadmill - 10 Feb',
    'Aerobic Treadmill - 5 May',
    '5K Pace Maintenance - 12 May',
    'Easy Continuous 5K - 19 May',
    '5K Standard Maintenance - 26 May',
    'Post-Match Flush Bike',
    'Prop Acceleration & Sled Power',
    'Prop Repeat-Effort Field Conditioning',
    'Prop Performance Check',
    'Treadmill Prep W1 - Mon 17 Aug',
    'Treadmill Prep W1 - Wed 19 Aug',
    'Treadmill Prep W1 - Fri 21 Aug',
    'Treadmill Prep W2 - Mon 24 Aug',
    'Treadmill Prep W2 - Wed 26 Aug',
    'Treadmill Prep W2 - Fri 28 Aug',
    'Treadmill Prep W3 - Mon 14 Sep',
    'Treadmill Prep W3 - Wed 16 Sep',
    'Post-Stag Treadmill - Mon 21 Sep',
    'Treadmill Prep W4 - Wed 23 Sep',
    'Treadmill Prep W4 - Fri 25 Sep',
    'Treadmill Prep W5 - Mon 28 Sep',
    'Treadmill Prep W5 - Wed 30 Sep',
    'Treadmill Prep W5 - Fri 2 Oct',
    'Treadmill + Rugby Integration - Mon 5 Oct',
    'Treadmill + Rugby Integration - Wed 7 Oct',
    'Treadmill + Rugby Integration - Fri 9 Oct',
    'Treadmill Prep W6 - Mon 12 Oct',
    'Treadmill Prep W6 - Wed 14 Oct',
    'Treadmill Prep W6 - Fri 16 Oct',
    'Treadmill Prep W7 - Mon 19 Oct',
    'Treadmill Prep W7 - Wed 21 Oct',
    'First Continuous 3K - Fri 23 Oct',
    'Continuous 3K - Mon 26 Oct',
    'Continuous 3.5K - Wed 28 Oct',
    'Treadmill Prep W2 - Mon 17 Aug',
    'Treadmill Prep W2 - Wed 19 Aug',
    'Treadmill Prep W2 - Fri 21 Aug',
    'Treadmill Prep W3 - Mon 24 Aug',
    'Treadmill Prep W3 - Wed 26 Aug',
    'Treadmill Prep W3 - Fri 28 Aug',
    'Treadmill Prep W4 - Mon 14 Sep',
    'Treadmill Prep W4 - Wed 16 Sep',
    'Treadmill Prep W5 - Wed 23 Sep',
    'Treadmill Prep W5 - Fri 25 Sep',
    'Treadmill Prep W6 - Mon 28 Sep',
    'Treadmill Prep W6 - Wed 30 Sep',
    'Treadmill Prep W6 - Fri 2 Oct',
    'Treadmill Prep W7 - Mon 12 Oct',
    'Treadmill Prep W7 - Wed 14 Oct',
    'Treadmill Prep W7 - Fri 16 Oct',
    'First Continuous 3K - Mon 19 Oct',
    'Post-Cruise Treadmill Build - Wed 16 Sep',
    'General Speed & Power',
    'Aerobic Power Bike Intervals',
    'Strength & Fitness Performance Check',
    'Off-Season Sprint Microdose',
    'Anaerobic Bike Repeats',
    'Prop Fitness Performance Check',
    'General Speed & Power Conditioning',
    'Aerobic Power Intervals',
    'Cruise Bike Repeat-Effort Intervals',
    'Cruise Stair Stepper Aerobic Power',
    'Cruise Incline Treadmill Conditioning',
    'Treadmill Maintenance Run',
    'Prop Sprint & Repeat-Effort Conditioning',
]

/** Mobility routines to remove. Checked in both Mobility and ConditioningSession. */
export const MOBILITY_REMOVE = [
    'Lower-Body Plyometric Foundations',
    'Lateral Power and Stability',
    'Rugby Power Plyometrics',
    'Low-Impact Plyometric Session',
    'Hip Mobility Flow',
    'Ankle and Calf Mobility',
    'Full-Body Mobility Reset',
    'Upper-Body and Shoulder Mobility',
    'Pre-Run Dynamic Mobility + Upper-Body Mobility',
]

/** Recovery items to remove. Checked in both Recovery and ConditioningSession. */
export const RECOVERY_REMOVE = [
    'Easy Recovery Walk',
    'Easy Recovery Bike',
    'Pool Recovery',
    'Sauna Recovery',
    'Hot Bath Recovery',
    'Foam Rolling Recovery',
    'Breathing and Relaxation',
    'Legs-Up Recovery',
    'Recovery Nap',
    'Low-Stimulation Evening',
    'Complete Rest Day',
]

/**
 * Removed exercise name -> the surviving exercise that workout lines should be
 * re-pointed at. These are wording variants of the same movement, so kept
 * workouts keep their line (and its sets/reps/notes) instead of losing it.
 * "Paused barbell back squat" folds into the plain back squat — the pause is a
 * prescription, and the line's own notes still carry it.
 */
export const EXERCISE_REPOINT: Record<string, string> = {
    'Trap-bar deadlift': 'Trap bar deadlift',
    'Seated or lying leg curl': 'Seated leg curl',
    'Standing dumbbell calf raise': 'Standing calf raise',
    'Paused barbell back squat': 'Barbell back squat',
}
